# .streamlit/secrets.toml

[supabase]
url = "https://dkbiurasbinrawvrtdtz.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrYml1cmFzYmlucmF3dnJ0ZHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQ1ODMxMTYsImV4cCI6MjA0MDE1OTExNn0.Bjg8I4PUMNHBfZumqQy_vOB5r1jZMRqBgXfchjrRQVg"